### ISSUE TITLE
RHOC / REV balances preview

### ISSUE THREAD

**Issue by dckc** [pmoorman/RChain-docs#1]
The coop announced the block height at which RHOC balances will be transfered to the RChain genesis block and become REV balances:
 - [RChain Mainnet announcement: the block height](https://blog.rchain.coop/blog/2020/01/23/rchain-mainnet-announcement-the-block-height/) Jan 23, 2020
 - [REV Issuance](https://developer.rchain.coop/token-swap) revised Jan 24, 2020

### Balances as of block 9371743

[wallets_9371743.txt](https://github.com/rchain-community/RChain-docs/files/4142663/wallets_9371743.txt)
sha1sum: `2e089d38d48b18f48fb969f34ae247ff7f4e0ca9`

That was generated using [rchain/rhoc-balance-reporter](https://github.com/rchain/rhoc-balance-reporter) 7a54a41 Aug 15  2019.

_I did a preview run with `BLOCK=9345273`. The result is: [wallets.txt](https://github.com/rchain-community/RChain-docs/files/4110010/wallets.txt)_

### Is RHOC in MEW Safe? (yes, assuming...)

If [MEW](https://www.myetherwallet.com/) shows an address that is in `wallets.txt`, then yes, it's safe, provided
  - the last column shows 0 (i.e. a plain Ethereum account, not a smart contract)
  - the RHOC did not get to that account via one of the [scam addresses](https://blog.rchain.coop/blog/2019/05/03/mitigating-the-barcelona-attack/)
    - see also [rchain/rbalance](https://github.com/rchain/rbalance) and [PR 5](https://github.com/rchain/rbalance/pull/5)
  - you have control of the private key for that account

See also

 - [Signing RChain transactions with Metamask and Ledger](https://www.youtube.com/watch?v=8Gkh5_ztqXw) Nov 20, 2019
 - [Jan 27 discussion in #wallet](https://discordapp.com/channels/375365542359465989/479351865457377290/671455869698965525)

#### Is a Ledger hardware wallet safe? (yes, assuming...)

If the wallet you use with your Ledger shows an address in `wallets.txt` then yes, it's safe, though the coop hasn't devoted resources to support that path immediately.

ref:
 - [RCHAIN-3866: Add support for Ethereum personal signature format #2789](https://github.com/rchain/rchain/pull/2789)
 - [Signing RChain transactions with Metamask and Ledger](https://www.youtube.com/watch?v=8Gkh5_ztqXw) Nov 20, 2019

**Comment by dckc** [comment]
### RHOC in contracts (at risk!)

> ... those wishing to have access to REV on the RChain network should make sure that their RHOCs are in an address for which they control the private key.

The 3rd column of `wallets.txt` is 1 when the address is an ethereum contract rather than a plain account with a key pair.

For example, the 2nd one is the coop Current operation account, according to [RChain RHOC Distribution](https://github.com/rchain/reference/blob/master/finance/rhoc.md)

_p.s. See also [note regarding coop multisig](https://discordapp.com/channels/375365542359465989/406191011564617748/671724090347880449)_

```
$ # select * from wallets where contract=1 order by balance desc
$ grep ,1$ wallets.txt |sort -nr -k2 -t,
0x1c73D4Ff97b9c8299F55D3b757B70979Ee718754,27466403837716800,1
0xd35a2d8c651F3eba4F0a044DB961b5B0CCf68a2d,7793221780308682,1
0x287550958BE9D74d7f7152C911BA0b71801153A8,3117693198495265,1
0xf15230Cba5B211B7Cb6A4ae7cFc5a84e9cb6865d,1420881000000000,1
0x821aA521Ecba3f4fdef89cBe1F468636e858d90d,400000000000000,1
0x8d12A197cB00D4747a1fe03395095ce2A5CC6819,123888875532825,1
0x2a0c0DBEcC7E4D658f48E01e3fA353F44050c208,33542049164080,1
0xFCb733335456AACB010b3ba2f6270C83E849eCC3,23055366800000,1
0x168296bb09e24A88805CB9c33356536B980D3fC5,1374504267036,1
0x097D850094aF2d8b50C099414fc0953AeeFe5022,802059300000,1
0x9a2d163aB40F88C625Fd475e807Bbc3556566f80,709000000000,1
0x1cE7AE555139c5EF5A57CC8d814a867ee6Ee33D8,625736445456,1
0x38c6A68304cdEfb9BEc48BbFaABA5C5B47818bb2,500000000000,1
0x21738172D0C17Fb5041AB5d7fe9B84914164482A,400000000000,1
0x2af47a65da8CD66729b4209C22017d6A5C2d2400,200000000000,1
0x85C5c26DC2aF5546341Fc1988B9d178148b4838B,97442948585,1
0x04F062809B244e37e7fDC21D9409469c989C2342,28089142976,1
0xF4342c8C8252c23C13E5Ce56EA51d9F24Ecf9012,10000000000,1
0xcf25EbD54120cF2e4137Fab0A91a7f7403A5DEbF,2992750000,1
0x8ab7fdE4B32e9Bd66734e550A145aeB12822681D,1500000000,1
0x394e524b47A3AB3D3327f7fF6629dC378c1494a3,851202141,1
0xbF45F4280Cfbe7C2D2515A7D984B8c71c15E82B7,492105856,1
0xCB60D600160D005845Ec999f64266D5608fd8943,334000000,1
0xb92102B5C12a1Bc4774ff53d720CB1660a842b94,200000000,1
0xbF29685856FAE1e228878DFB35B280C0adCC3B05,113911827,1
0xf8700dFfaBaC07A280069419298545387B4D5357,100000000,1
0xB5ed18405949DB4aBC029077533115f63D80996f,6076000,1
0x4D71b91D46fA7247870804601E53AD9330CC7dCe,1190622,1
0xdC36CbE88eFD1b4Ef5cDcdbe74f0B28cd1e23D12,920000,1
0x14a4617C7A95046546541973797e44df7770f837,900000,1
0x980cAe4F2C7301D1D23FC709C379657C90D27D52,666833,1
0x6Ab7b546C392f62a8E1c4d483241FF605369f4de,600000,1
0x6924d3ad691E7F641FFe1c95aa6297e4C10e5e86,278000,1
0xd52Bc4fE5DA20BA35f25b38581c805B165211f99,237857,1
0x82da82DBe384736e4Dd95615D8036Cc472773F5A,200001,1
0xB4bCCD6095D9C0fbDf93c06c260384fb76c41ef5,199214,1
0x409B512e1cf94500877C5353B2a0C13B2d24914F,89787,1
0xbAd7653bc486c44FBeafa23FdEd6b3F3112D321C,6000,1
0x8018280076d7fA2cAa1147e441352E8a89e1DDbe,1,1
```

**Comment by dckc** [comment]
### KuCoin wallets are plain accounts

not a (multisig) contract. I got the addresses from @ysgjay in an RChain telegram channel

```
~/projects/rhoc-balance-reporter$ grep -i 0x2b5634c42055806a59e9107ed44d43c426e58258 wallets.txt 
0x2B5634C42055806a59e9107ED44D43c426E58258,435380935559725,0

~/projects/rhoc-balance-reporter$ grep 0x2B5634C42055806a59e9107ED44D43c426E58258 wallets.txt 
0x2B5634C42055806a59e9107ED44D43c426E58258,435380935559725,0
```

**Comment by dckc** [comment]
### snapshot block ETA Tue Jan 28 2020 10:54:10 GMT-0600 (Central Standard Time)

etherscan API projects block 9371743 will arrive at this time

**Comment by dckc** [comment]
### Balances as of block 9371743

and sorted by address:

[wallets_9371743.txt](https://github.com/rchain-community/RChain-docs/files/4125610/wallets_9371743.txt)

See also [note regarding coop multisig](https://discordapp.com/channels/375365542359465989/406191011564617748/671724090347880449)

**Comment by dckc** [comment]
I put the balances into a SQL table you can play with: https://repl.it/join/mujzsfzg-dckc

**Comment by woky** [comment]
@dckc it seems you've sorted the result. Could you please publish unsorted version? By default addresses are added in order they first appear in a transfer.

**Comment by dckc** [comment]
OK, I ran it again to get unsorted results:

[wallets_9371743.txt](https://github.com/rchain-community/RChain-docs/files/4142663/wallets_9371743.txt)


```
rhoc-balance-reporter$ sha256sum wallets_9371743.txt 
308fce89369188e68873412c6e60b9c8481bd57e76fb9cc89d23458fa79105de  wallets_9371743.txt
rhoc-balance-reporter$ sha1sum wallets_9371743.txt 
2e089d38d48b18f48fb969f34ae247ff7f4e0ca9  wallets_9371743.txt
```

**Comment by Phistr90** [comment]
> OK, I ran it again to get unsorted results:
> 
> [wallets_9371743.txt](https://github.com/rchain-community/RChain-docs/files/4142663/wallets_9371743.txt)
> 
> ```
> rhoc-balance-reporter$ sha256sum wallets_9371743.txt 
> 308fce89369188e68873412c6e60b9c8481bd57e76fb9cc89d23458fa79105de  wallets_9371743.txt
> rhoc-balance-reporter$ sha1sum wallets_9371743.txt 
> 2e089d38d48b18f48fb969f34ae247ff7f4e0ca9  wallets_9371743.txt
> ```

I can confirm thats the same balance file I get when querying the bc with the given tool.

`[pi@pi rhoc-balance-reporter]$ sha256sum wallets.txt 
308fce89369188e68873412c6e60b9c8481bd57e76fb9cc89d23458fa79105de  wallets.txt`

Sanity check:
TotalSupply = 1 billion Rhoc
Sum over all balances = 10^17
Rhoc contract specifies 8 decimals => 
SumOfAllBalances = 10^(17-8) Rhoc=10^9 Rhoc = 1 billion Rhoc = TotalSupply

This matches the expected total supply.

**Comment by dckc** [comment]
mainnet launched.

https://github.com/rchain/rchain/commit/cf10e26f537e516fb3ebcb5e9b9d77f1e0b907f0#diff-14230f61bd79457f34c0e11b9f121f6a (I note a couple edits since then; hmm...)
https://discordapp.com/channels/375365542359465989/454113117257859073/678444912827432969 my own endorsement of wallets.txt cf10e26
https://github.com/dckc/rbalance/blob/check_rev/TEST.rst 4b608c0 my audit
